---
grails:
    profile: web
    codegen:
        defaultPackage: xyz.ekkor
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    encrypt:
        key: "asdf"

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
#    h2:
#        console:
#            enabled: true
#            path: /console
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
#dataSource:
#    pooled: true
#    jmxExport: true
#    driverClassName: org.h2.Driver
    #driverClassName: oracle.jdbc.driver.OracleDriver
    #dialect: org.hibernate.dialect.Oracle10gDialect
    #driverClassName: com.mysql.cj.jdbc.Driver
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    username: eunsebi
#    password: 'assa1332!'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: 1234

environments:
    development:
        dataSource:
            dbCreate: create-drop
            #url: jdbc:oracle:thin:@//oracleinstance.cgthqszcfuqa.ap-northeast-2.rds.amazonaws.com:1521:eunsebi
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            #url: jdbc:mysql://ekkor.cgthqszcfuqa.ap-northeast-2.rds.amazonaws.com/devDb
        grails:
            serverUrl: "http://localhost:8080/${appName}"
            dbconsole:
                enabled: true
                urlRoot: '/admin/dbconsole'
    test:
        dataSource:
            dbCreate: update # 'create-drop', 'create', 'update' or 'validate' - 'none' or any other value - does nothing
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update # 'create-drop', 'create', 'update' or 'validate' - 'none' or any other value - does nothing
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            #url: jdbc:mysql://ekkor.cgthqszcfuqa.ap-northeast-2.rds.amazonaws.com/devDb
            #url: jdbc:oracle:thin:@//oracleinstance.cgthqszcfuqa.ap-northeast-2.rds.amazonaws.com:1521/eunsebi
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
